name: Run CI make command

on:
  push:
    branches:
    - "*"
    - "!main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        working-directory: .
        run: |
          touch ~/.v20.conf
          echo "hostname: api-fxpractice.oanda.com" >> ~/.v20.conf
          echo "streaming_hostname: stream-fxpractice.oanda.com" >> ~/.v20.conf
          echo "port: 443" >> ~/.v20.conf
          echo "ssl: true" >> ~/.v20.conf
          echo "token: ${{ secrets.OANDA_TOKEN }}" >> ~/.v20.conf
          echo "username: ${{ secrets.OANDA_USERNAME }}" >> ~/.v20.conf
          echo "accounts:" >> ~/.v20.conf
          echo "- ${{ secrets.OANDA_ACCOUNT }}" >> ~/.v20.conf
          echo "active_account: ${{ secrets.OANDA_ACCOUNT }}" >> ~/.v20.conf

          make ci